export const CUSTOMER_NAME_MAX_LENGTH = 24;
export const CUSTOMER_NAME_KANA_MAX_LENGTH = 48;
export const CUSTOMER_EMAIL_MAX_LENGTH = 255;
export const CUSTOMER_URL_MAX_LENGTH = 1024;
export const CUSTOMER_ADDRESS_MAX_LENGTH = 255;
export const CUSTOMER_NOTE_MAX_LENGTH = 4096;
